name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt
      - uses: actions/checkout@v3
      - name: Install cargo-hack
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-hack
      - name: Install cargo-machete
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-machete
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
      - name: Check fmt
        run: cargo fmt -- --check
      - name: Check unused dependencies
        run: cargo machete
      - name: Check features
        run: cargo hack check --all --ignore-private --each-feature --no-dev-deps
      - name: Check all targets
        run: cargo check --all --all-targets --all-features

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    env:
      RUSTFLAGS: "-D warnings"
      # run a lot of quickcheck iterations
      QUICKCHECK_TESTS: 1000

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --all --all-features

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@v3

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
